#!/bin/bash

rm -rf debian
cp -r debian.theia debian

fakeroot debian/rules clean

if [ -d security/tomoyo/policy ]; then
	mkdir -p debian/build/build-generic/security/tomoyo
	cp -r security/tomoyo/policy debian/build/build-generic/security/tomoyo/
fi

skipdbg=false \
DEB_BUILD_OPTIONS=parallel=8 \
NOEXTRAS=1 \
CROSS_COMPILE=`pwd`/debian.master/bin/ \
AUTOBUILD=1 \
fakeroot debian/rules binary-generic

# The previous command sometimes fails on the first try

if [[ $? -ne 0 ]]; then
skipdbg=false \
DEB_BUILD_OPTIONS=parallel=8 \
NOEXTRAS=1 \
CROSS_COMPILE=`pwd`/debian.master/bin/ \
AUTOBUILD=1 \
fakeroot debian/rules binary-generic
fi

# If it still fails, give up!

if [[ $? -ne 0 ]]; then
	exit $?
fi

skipdbg=false \
DEB_BUILD_OPTIONS=parallel=8 \
NOEXTRAS=1 \
CROSS_COMPILE=`pwd`/debian.master/bin/ \
AUTOBUILD=1 \
fakeroot debian/rules binary-headers

# The previous command sometimes fails on the first try

if [[ $? -ne 0 ]]; then
skipdbg=false \
DEB_BUILD_OPTIONS=parallel=8 \
NOEXTRAS=1 \
CROSS_COMPILE=`pwd`/debian.master/bin/ \
AUTOBUILD=1 \
fakeroot debian/rules binary-headers
fi

exit $?
