#!/bin/bash

if [ ! -d debian ]; then
	cp -r debian.theia debian
fi

fakeroot debian/rules clean

if [ -d security/tomoyo/policy ]; then
	mkdir -p debian/build/build-generic/security/tomoyo
	cp -r security/tomoyo/policy debian/build/build-generic/security/tomoyo/
fi

skipdbg=false \
DEB_BUILD_OPTIONS=parallel=8 \
NOEXTRAS=1 \
CROSS_COMPILE=`pwd`/debian.master/bin/ \
AUTOBUILD=1 \
fakeroot debian/rules binary-generic binary-headers

# The previous command sometimes fails on the first try

if [[ $? -ne 0 ]]; then
skipdbg=false \
DEB_BUILD_OPTIONS=parallel=8 \
NOEXTRAS=1 \
CROSS_COMPILE=`pwd`/debian.master/bin/ \
AUTOBUILD=1 \
fakeroot debian/rules binary-generic binary-headers
fi

exit $?
