#!/bin/bash

#find the location of this script
#and assume that it is in the theia-ki-target-agent/linux-lts-quantal-3.5.0 dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#exit on error from any command
set -e

#run this script like "BUILD_DIR=other_dir ./compile" to override
if [ -z "${BUILD_DIR}" ]; then
  BUILD_DIR=theia_build
fi

num_cores=`cat /proc/cpuinfo | grep processor | wc -l`
build_parallel=$(($num_cores+1))

CC=gcc
#use ccache if available
if which ccache >/dev/null; then
  CC="ccache gcc"
fi

#create build dir if needed
if [ ! -d "${DIR}/${BUILD_DIR}" ]; then
  mkdir "${DIR}/${BUILD_DIR}"
fi

#copy theia kernel config if needed
if [ ! -f "${DIR}/${BUILD_DIR}/.config" ]; then
  cp "${DIR}/theia.64.config" "${DIR}/${BUILD_DIR}/.config"
fi

#remove pesky directory that makes Kbuild think things are not clean
if [ -d "${DIR}/include/config" ]; then
  rmdir "${DIR}/include/config"
fi

#build everything
make -j$build_parallel O="${DIR}/${BUILD_DIR}" CC="$CC"
